### ISSUE TITLE
Alcatraz not compatible with the last version of Xcode

### ISSUE THREAD

**Issue by peyotll** [wakatime/xcode-wakatime#10]
For each release of Xcode you depend on Alcatraz project, do you plan to use another system? Because right now I can't use Wakatime and have to wait for an update of Alcatraz... It's quite annoying.

**Comment by alanhamlett** [comment]
What version of Xcode? Alcatraz should work with Xcode <= v6.3 unless it's some how broken right now?

**Comment by peyotll** [comment]
Version 6.3.2. Yes it's related to those 2 issues.

**Comment by alanhamlett** [comment]
Ok, looks like they just released a new version with support for Xcode 6.3.2.

This is an ongoing issue, but Alcatraz maintainers have said they don't want to automate new DVTPlugInCompatibilityUUID updates.

**Comment by nikhilsh** [comment]
Hi Alan, could you add support for 6.3.2 with this string?
E969541F-E6F9-4D25-8158-72DC3545A6C6

**Comment by alanhamlett** [comment]
Sure, just added with 78332606e1b4d049585e484156bc43b2ff7fabb7.
