### ISSUE TITLE
Not working in Xcode 6.4

### ISSUE THREAD

**Issue by MatthewCawley** [wakatime/xcode-wakatime#12]
Hi,

I cannot get this to work with Xcode 6.4.

Viewing the syslog, I get the following error:

Jul  3 04:47:00 MiM Xcode[12046] <Warning>: [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin' not present in DVTPlugInCompatibilityUUIDs

I checked the plist embedded in the WakaTime.xcplugin file and the UUID exists, so for some reason it isn't being picked up. Is there some form of plugin cache that is loading an older version?

**Comment by alanhamlett** [comment]
Can you open the Plugin Manager window to force Alcatraz to check for plugin updates?

**Comment by MatthewCawley** [comment]
I've tried that several times, including deleting the plugin, re-installing etc.

**Comment by MatthewCawley** [comment]
Ok, it has randomly started working after an uninstall and reinstall - not sure why or what the issue was. It is possibly an issue with my system or Xcode. Glad its all working now :) Thanks
