### ISSUE TITLE
OSX, serious performance degradation 

### ISSUE THREAD

**Issue by seregasheypak** [wakatime/xcode-wakatime#14]
Hi, we have two IOS developers using XCode and they experience performance problems after installing wakatime plugin.
OS X Yosemite 10.10.5
Xcode: 7.0(7A220)
Sometimes XCode starts to work slowly. Text editor Scroll becomes unresponsive or slow. Sometimes Xcode "Navigator" window stops to respond on clicks. It's impossible to choose file to edit by clicking "Navigator" tab. 
If developer restarts XCode it starts to work normally for some period of time.
We didn't see such problems before installing wakatime.

**Comment by alanhamlett** [comment]
Closing since this is probably fixed by now. @seregasheypak, I'll reopen it if this is still occurring for you?
