### ISSUE TITLE
'Unknown Project'

### ISSUE THREAD

**Issue by leo150** [wakatime/xcode-wakatime#15]
Hi, thank you for nice plugin
I use CocoaPods so I need to work inside workspace including two projects - mine and Pods. Problem is that dashboard shows project opened through workspace as 'Unknown Project'. How can I fix that? 

![screen shot 2015-12-06 at 20 48 43](https://cloud.githubusercontent.com/assets/3484524/11614756/f8dfbb68-9c5c-11e5-9afd-48da670e18ff.png)

**Comment by alanhamlett** [comment]
There are many ways to set the project going forward (`~/.wakatime.cfg` file, `.wakatime-project` file, using revision control like git). The easiest way is create a file named `.wakatime-project` in your project's top-level folder with the first line containing the name of the project.

To rewrite your coding activity after creating the `.wakatime-project` file, add a [custom rule](https://wakatime.com/settings/rules) saying "If file contains X, set project to Y".

**Comment by leo150** [comment]
@alanhamlett thanks, it works!
