### ISSUE TITLE
new Xcode plugin for Xcode 8?

### ISSUE THREAD

**Issue by AndrewSB** [wakatime/xcode-wakatime#18]
Now that Xcode 8 has first party support for extensions, it would be awesome for this to work without Alcatraz!

**Comment by alanhamlett** [comment]
Official Xcode extension can currently only run when the user selects them from a menu, which means no automatic metrics yet. A lot of people have filed Radars (Apple bug reports) so hopefully they improve their extension api soon:

https://wakatime.com/blog/25-xcode-8-will-disable-all-your-plugins

**Comment by AndrewSB** [comment]
Ahh, thats super unfortunate, didn't realize the new extensions had to be initiated by a user 😦 
I can close this issue, or we can leave it open to track this problem 😬

**Comment by akaralar** [comment]
@alanhamlett is there an open radar link so that we can dupe it on radar?

**Comment by alanhamlett** [comment]
Some people have posted the contents of their Radar here:
https://github.com/alcatraz/Alcatraz/issues/475

If you create a new [bug report](https://bugreport.apple.com/) with the same contents, Apple will mark it as a duplicate and let you see the original Radar's status changes, but other people's Radars are private.

**Comment by alanhamlett** [comment]
New install instructions for Xcode 8 available:
https://github.com/wakatime/xcode-wakatime#installation
