### ISSUE TITLE
XCode 8.1 and WakaTime / Alcatraz

### ISSUE THREAD

**Issue by patsch** [wakatime/xcode-wakatime#19]
I followed the [instructions](https://github.com/wakatime/xcode-wakatime) to patch XCode 8 using MakeXcodeGr8Again however when I launch the patched XCode there is no "Package Manager" menu in the "Window" menu of XCode and it's not clear to me whether WakaTime  is running or not.

I re-installed Alcatraz several times after patching XCode but it didn't seem to make any difference.

Any suggestions ?

**Comment by alanhamlett** [comment]
Some people are having luck following these instructions:

https://github.com/alcatraz/Alcatraz/issues/498

**Comment by nobre84** [comment]
@alanhamlett I've upgrade to Xcode 8.2 and resigned it to install extensions, however despite being listed in Xcode menu and showing my Wakatime API key, nothing is logged! Other extensions such as Package Manager and VVDocumenter work fine. Do you have any idea or some log file at which I could try and troubleshoot this ? Doing contract work without Wakatime is unbearable!

**Comment by nobre84** [comment]
Nevermind! I managed to see many loading errors in Console.app such as 
```
WARNING: Failed to load plugin at path: "~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin", skipping. Error: Error Domain=NSCocoaErrorDomain Code=3587 "dlopen_preflight(~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin/Contents/MacOS/WakaTime): no suitable image found.  Did find:
		~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin/Contents/MacOS/WakaTime: mmap() error 1 at address=0x111444000, size=0x00006000 segment=__TEXT in Segment::map() mapping ~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin/Contents/MacOS/WakaTime" UserInfo={NSLocalizedFailureReason=The bundle is damaged or missing necessary resources., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin/Contents/MacOS/WakaTime, NSDebugDescription=dlopen_preflight(~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin/Contents/MacOS/WakaTime): no suitable image found.  Did find:
		~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin/Contents/MacOS/WakaTime: mmap() error 1 at address=0x111444000, size=0x00006000 segment=__TEXT in Segment::map() mapping ~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin/Contents/MacOS/WakaTime, NSBundlePath=~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin, NSLocalizedDescription=The bundle “WakaTime” couldn’t be loaded because it is damaged or missing necessary resources.}
```

After opening my self signed certificate and marking it as Always Trusted, it started working. Funny thing the other plugins worked despite throwing similar warnings in the console.

**Comment by alanhamlett** [comment]
New install instructions for Xcode 8 available:
https://github.com/wakatime/xcode-wakatime#installation
