### ISSUE TITLE
Wakatime crashes Xcode 8.3 repeatedly, how to uninstall!?!?

### ISSUE THREAD

**Issue by HeidiHansen** [wakatime/xcode-wakatime#23]
I can't navigate to any files in my project using the nav keybinding Shift-Command-O.  If I do that, the app crashes, repeatedly.  I reopen, and it crashes again.  I try to write code, it crashes again.  This is speicfic to wakatime- I have nothing else installed and I have made no other changes.  Please tell me how to completely remove this plugin so I can keep working.. I can't use Xcode at all until I get this removed.  I don't want to troubleshoot this, I just want it gone.  Why aren't there clear and easily findable removal instructions? 

I have followed the delete steps here, but clearly this isn't enough.  Instead of helping me with work, this is making me incapable of working.  =(  https://github.com/wakatime/xcode-wakatime/issues/7

**Comment by HeidiHansen** [comment]
Update, I wasted an hour deleting xcode, emptying trash, restarting computer, opening app store, and reinstalling xcode.  Works fine now.  Please provide a better solution for others who encounter the same issue.

**Comment by alanhamlett** [comment]
Added [Uninstall Instructions](https://github.com/wakatime/xcode-wakatime#uninstalling) with f63010b626f24c808b6d95b6959a3482e2e9689b. Make sure to delete `~/.wakatime.cfg` since it contains your secret api key.
