### ISSUE TITLE
xCode 9.. even worse than 8 for wakatime!

### ISSUE THREAD

**Issue by cucumbur** [wakatime/xcode-wakatime#25]
xCode 9 seems incompatible with all of the different methods of getting xCode 8 to work with waka hacks and so on. I am a dev but I've never really done mobile development besides non-native, so I'm new to XCode and the whole way things are organized. So, excuse my ignorance but is there anything that can be done now to make this work for XCode 9?
(I think I saw something about being able to build with XCode 8 but given that i have 2b of free space, I don't think that was intentional and I don't know how to access it separately.

**Comment by HiroshiHorie** [comment]
I want it working with Xcode9 somebody please 🙏

**Comment by alanhamlett** [comment]
Re-run the install command and it will work for Xcode 9:

`curl -fsSL https://raw.githubusercontent.com/wakatime/xcode-wakatime/master/install.sh | sh`

**Comment by cucumbur** [comment]
Eh I guess it's working for a lot of other people, but all this unsigning and re-signing and certificates and shell scripts that are inscrutable. I read all the threads on the alcatraz repo and some people may be able to get it working, but I would still say that theres no compatibility with xcode 9 the same way I would say windows desktop applications are compatible with mac. (that is, its possible to get it working by jumping through hoops by not by default)

**Comment by HiroshiHorie** [comment]
I can not install, I get the following error:

** BUILD FAILED **

The following build commands failed:
	PhaseScriptExecution Run\ Script build/WakaTime.build/Release/WakaTime.build/Script-E65F85E918D187D30082F26A.sh

**Comment by alanhamlett** [comment]
@HiroshiHorie that's going to be fixed with #26.
