### ISSUE TITLE
Does it work for XCode 9?

### ISSUE THREAD

**Issue by coffeeplanter** [wakatime/xcode-wakatime#27]
Hi! Does it work for XCode 9? I can't resign XCode while installation script running. Using High Sierra. And getting this terminal output:
>/Applications/Xcode.app: replacing existing signature
>/Applications/Xcode.app: unknown error -1=ffffffffffffffff

**Comment by alanhamlett** [comment]
Yes, it worked for me after upgrading to Xcode 9.1 and re-running the install script. Does Xcode open and ask you to load bundles?

**Comment by coffeeplanter** [comment]
Alan, thanks, I tried to run the script on XCode 9.0.1 (not 9.1), and the IDE didn't asked me anything after this. I tried several times. I'll be able to upgrade and check again later in some days.

**Comment by alanhamlett** [comment]
When you re-ran the install script did it show the same `unknown error -1` again?

```curl -fsSL https://raw.githubusercontent.com/wakatime/xcode-wakatime/master/install.sh | sh```

**Comment by coffeeplanter** [comment]
Yes, I ran this script several times, and every time I had the same error.

**Comment by coffeeplanter** [comment]
I updated to the version 9.1, and the Wakatime plugin is working fine now.
