### ISSUE TITLE
Make distinction between different machines

### ISSUE THREAD

**Issue by funky-monkey** [wakatime/xcode-wakatime#3]
As a freelancer I need to track my time accurately. When working on different machines (home, work) it would be great to distinguish between then and see the difference in the time rapports, so I can see what I worked on and where.

**Comment by alanhamlett** [comment]
We've added `machine name` as a vector for the metrics, but it's currently only displayed via API and not on the website dashboard:

https://wakatime.com/developers/#summaries
and
https://wakatime.com/developers/#stats
