### ISSUE TITLE
wakatime cli unicode tests cause error when extracting

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/xcode-wakatime#30]
Unicode characters in a test file cause an error when the install script extracts the wakatime cli zip archive.
https://github.com/wakatime/wakatime/blob/5bf2c063a55c340d70131a6c1cd6ab014cadaf3f/tests/samples/codefiles/unicode/%C3%A0-%C3%BC%C3%B1%C3%AE%C4%8D%C3%B5d%C4%99-f%C3%AC%C5%82%C3%AB.txt

```
<snap>
Alcatraz successfully installed!!1!🍻  Please restart your Xcode (9.2).
<snap>
** CLEAN SUCCEEDED **
<snap>
error:  cannot create wakatime-master/tests/samples/codefiles/unicode/+\341-+++\246+\253-\354+\301d-\326-f+\274+\351+\275.txt
        Illegal byte sequence
<snap>
Command /bin/sh emitted errors but did not return a nonzero exit code to indicate failure
<snap>
```

**Comment by alanhamlett** [comment]
@hao-li can you try re-installing and see if it works now?

**Comment by hao-li** [comment]
Thank you, this error has disappeared.
But the 'XcodeSigner: no identity found' error is still, I have opened a new issue #31.
