### ISSUE TITLE
Xcrun Error

### ISSUE THREAD

**Issue by torinberger** [wakatime/xcode-wakatime#32]
When I execute `curl -fsSL https://raw.githubusercontent.com/wakatime/xcode-wakatime/master/install.sh | sh` on macOS sierra, with xcode installed, I get the following error: `xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH`
Any ideas how to fix?

**Comment by alanhamlett** [comment]
Does `/usr/bin/xcodebuild` exist on your computer?

**Comment by torinberger** [comment]
nvm, not using Xcode anymore

**Comment by alanhamlett** [comment]
Fixed with 71597d84ecfc16e83a780bafc6fa561ee7f2292e.
