### ISSUE TITLE
XCode 10 beta support?

### ISSUE THREAD

**Issue by Zeta611** [wakatime/xcode-wakatime#34]
I'm trying to use WakaTime on Xcode 10 beta, but I can't seem to find a way to use it.
After some Googling, I found out that XCode package manager Alcatraz does not support recent XCode releases.
Is there a way to use WakaTime on Xcode 10 beta?

I'm on macOS Mojave version 10.14 beta (18A384a), using Xcode Version 10.0 beta 6 (10L232m)

**Comment by alanhamlett** [comment]
Have you run the install script? It should upgrade Alcatraz and WakaTime packages to work with Xcode 10 Beta:

```
curl -fsSL https://raw.githubusercontent.com/wakatime/xcode-wakatime/master/install.sh | sh
```

**Comment by Zeta611** [comment]
@alanhamlett Yes, I did, and also with ‘-s beta’ flag. Neither an api code prompt nor Xcode info on the dashboard shows up. I also checked Xcode 9, which is installed alongside Xcode 10 beta, and there was no effect on it too.

**Comment by alanhamlett** [comment]
It's well tested with Xcode 9, so it's probably not related to the Xcode 10 version. Do you have a WakaTime API Key menu inside Xcode's File menu? Is there a `~/.wakatime.log` file with any error message?

**Comment by RSady** [comment]
I'm actually having the same issue.  Worked perfectly fine on Xcode9...to the point where i subscribed to be able to view my history for more than 14 days.  Installed Xcode10 beta, and even re-installed WakaTime, and it doesn't show up.  I removed Xcode 9 AND Xcode10 beta to install Xcode 10 GM, reinstalled WakaTime, and no dice.  I'm not even getting any error relating to it in the Xcode log OR the system.log file.

**Comment by Zeta611** [comment]
@alanhamlett 
I removed WakaTime via
`rm -r "${HOME}/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin"
rm "${HOME}/.wakatime.cfg"
rm -r "${HOME}/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin"`
and tried re-installing using both 
`curl -fsSL https://raw.githubusercontent.com/wakatime/xcode-wakatime/master/install.sh | sh`
and 
`curl -fsSL https://raw.githubusercontent.com/wakatime/xcode-wakatime/master/install.sh | sh -s beta`.

I still cannot see WakaTime menu item in File menu in both Xcode 9.4.1 and Xcode 10.0 beta 6.

When I re-installed WakaTime plugin, `** CLEAN FAILED **` is shown:
`Alcatraz successfully installed!!1!🍻  Please restart your Xcode (10.0).
Installing WakaTime...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--   100   131    0   131    0     0    205      0 --:--:-- --:--:-- --:--:--   205
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--   100 15882    0 15882    0     0  11428      0 --:--:--  0:00:01 --:--:-- 43994
x xcode-wakatime-master/
x xcode-wakatime-master/.gitignore
x xcode-wakatime-master/AUTHORS
x xcode-wakatime-master/HISTORY.rst
x xcode-wakatime-master/LICENSE
x xcode-wakatime-master/README.md
x xcode-wakatime-master/WakaTime.xcodeproj/
x xcode-wakatime-master/WakaTime.xcodeproj/project.pbxproj
x xcode-wakatime-master/WakaTime.xcodeproj/project.xcworkspace/
x xcode-wakatime-master/WakaTime.xcodeproj/project.xcworkspace/contents.xcworkspacedata
x xcode-wakatime-master/WakaTime/
x xcode-wakatime-master/WakaTime/WakaTime-Info.plist
x xcode-wakatime-master/WakaTime/WakaTime-Prefix.pch
x xcode-wakatime-master/WakaTime/WakaTime.h
x xcode-wakatime-master/WakaTime/WakaTime.m
x xcode-wakatime-master/WakaTime/XcodeClasses.h
x xcode-wakatime-master/WakaTime/en.lproj/
x xcode-wakatime-master/WakaTime/en.lproj/InfoPlist.strings
x xcode-wakatime-master/WakaTime/extract_xcode_plugin_uuid.py
x xcode-wakatime-master/WakaTime/install_dependencies.sh
x xcode-wakatime-master/XcodeSigner2018.cert
x xcode-wakatime-master/XcodeSigner2018.p12
x xcode-wakatime-master/XcodeSigner2018.pem
x xcode-wakatime-master/install.sh
2018-09-13 14:17:44.797 xcodebuild[52491:243692] [MT] PluginLoading: Required plug-in compatibility UUID 26355AE5-C605-4A56-A79B-AD4207EA18DD for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
note: Using new build system
error: Could not delete `/Users/jay` because it was not created by the build system and it is not a subfolder of derived data.

** CLEAN FAILED **

note: Using new build system
note: Planning build
note: Constructing build description`
Is it somehow related to this issue?

Also, the following is the log shown via `sudo tail -f /var/log/system.log`
`
Sep 13 14:19:05 MacJay com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.IDECacheDeleteAppExtension.52629): Path not allowed in target domain: type = pid, path = /Applications/Xcode.app/Contents/Frameworks/IDEKit.framework/Versions/A/XPCServices/IDETouchBarSimulatorService.xpc error = 147: The specified service did not ship in the requestor's bundle, origin = /Applications/Xcode.app/Contents/PlugIns/IDECacheDeleteAppExtension.appex
Sep 13 14:19:05 MacJay com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.IDECacheDeleteAppExtension.52629): Path not allowed in target domain: type = pid, path = /Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Versions/A/XPCServices/RootDebuggingXPCService.xpc error = 147: The specified service did not ship in the requestor's bundle, origin = /Applications/Xcode.app/Contents/PlugIns/IDECacheDeleteAppExtension.appex
Sep 13 14:19:07 MacJay com.apple.xpc.launchd[1] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for integer: _DirtyJetsamMemoryLimit
Sep 13 14:20:40 MacJay Xcode[52699]: DEPRECATED USE in libdispatch client: dispatch source activated with no event handler set; set a breakpoint on _dispatch_bug_deprecated to debug
Sep 13 14:20:40 MacJay com.apple.xpc.launchd[1] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for integer: _DirtyJetsamMemoryLimit
Sep 13 14:20:40 MacJay com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.Xcode.52699): Failed to bootstrap path: path = /Applications/Xcode-beta.app/Contents/XPCServices/com.apple.dt.Xcode.SymbolicateXPCService.xpc, error = 129: The service was superseded by a later version
Sep 13 14:20:45 MacJay Xcode[52714]: DEPRECATED USE in libdispatch client: dispatch source activated with no event handler set; set a breakpoint on _dispatch_bug_deprecated to debug
Sep 13 14:20:46 MacJay com.apple.xpc.launchd[1] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for integer: _DirtyJetsamMemoryLimit
Sep 13 14:20:50 MacJay LegacyExternalColorPickerService[52746]: DEPRECATED USE in libdispatch client: dispatch source activated with no event handler set; set a breakpoint on _dispatch_bug_deprecated to debug
Sep 13 14:20:56 MacJay com.apple.xpc.launchd[1] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for integer: _DirtyJetsamMemoryLimit
Sep 13 14:21:26 --- last message repeated 1 time ---
`

With verbose enabled in `~/.wakatime.cfg` file with `debug = true`, I only see vim-wakatime related logs.

@RSady So is WakaTime not working in both Xcode 9 and 10?

**Comment by k4reemMoustafa** [comment]
I updated Xcode to Version 10.0 (10A254a). I was unable to install wakatime plugin. I got this message in the system log: 

> com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.Xcode.752): Failed to bootstrap path: path = /Applications/Xcode.app/Contents/XPCServices/com.apple.dt.Xcode.SymbolicateXPCService.xpc, error = 129: The service was superseded by a later version

Please help.

**Comment by k4reemMoustafa** [comment]
It's named correctly but this time your script worked although I ran it many times before. Maybe there were a typo or something.

Thanks a lot :)

**Comment by RSady** [comment]
All is working again!  Thanks!

**Comment by Zeta611** [comment]
Works great! Thanks 😄
