### ISSUE TITLE
Wakatime not registering anything

### ISSUE THREAD

**Issue by fbarraganef** [wakatime/xcode-wakatime#37]
Hello, 
I installed wakatime many times and even I reinstalled my xcode and I'm  still not registering my working time on the dashboards. 

The steps I follow are : 
- Close xcode
- Run command in Terminal 
- Enter my password 
- Wait, wait and wait... 
- The xcode is launched, enter the key and then click on the load bundles option. 

and should be log my time but it didn't. 

The wakatime log is registering the changes but in the team ranking I'm always in zeros hours/mins. 

My setup is: 
xCode: 10.1
Mac:  Mojave 10.14.2 

I appreciate if anyone can help with the possible reason of my problem. 

Thanks, 
Francisco

**Comment by fbarraganef** [comment]
I just the received the email from wakatime from my time coding. But in the team option, I'm always in 0 mins 0 mins

**Comment by alanhamlett** [comment]
This was a problem with the team GitHub integration filter, but it's fixed now.

**Comment by fbarraganef** [comment]
> This was a problem with the team GitHub integration filter, but it's fixed now.

I reinstalled the wakatime plugin into my xcode for check it out, and I still in 0's, my report from coding activity in my projects shows work, but the teams report not. 

I already enable the logging and with the every change is sending the information correctly.

**Comment by alanhamlett** [comment]
The reason your coding activity is 0s on your organization's dashboard is because your projects are filtered from your org's GitHub integration.

Ask your organization admin to add your project names as whitelists in the organization's privacy settings to fix the issue.

**Comment by fbarraganef** [comment]
I saw the github integration into the privacy settings link that you sent me and my repo is there.
