### ISSUE TITLE
replacing existing signature

### ISSUE THREAD

**Issue by ienjoylife0525** [wakatime/xcode-wakatime#38]
Always stock at `/Applications/Xcode.app: replacing existing signature`
Need help !

**Comment by felixsolorzano** [comment]
Same for me

**Comment by fenixsolorzano** [comment]
10.1 @alanhamlett

**Comment by alanhamlett** [comment]
Just pushed a fix when running the default install command, but probably unrelated to this bug. Doesn't hurt to retry the install anyway.

I wasn't able to reproduce the signature error myself. Are you entering your OS X login password when prompted on command line and 2 GUI prompts?

**Comment by gandarez** [comment]
@alanhamlett what's the status of this issue?

**Comment by alanhamlett** [comment]
@fenixsolorzano and @ienjoylife0525 is this error still occurring with the latest master version?

**Comment by gandarez** [comment]
Feel free to reopen this issue.

**Comment by Ldoy** [comment]
My Xcode version is 13.3 and I faced this same error 🥲
