### ISSUE TITLE
Plugin stopped working on Xcode 10.1 25 days ago

### ISSUE THREAD

**Issue by k4reemMoustafa** [wakatime/xcode-wakatime#39]
The wakatime plugin stopped tracking time on Xcode 10.1
I tried to re-install, upgrade and remove and nothing helped.
Please help!
Kareem

**Comment by k4reemMoustafa** [comment]
Yes. It’s there. 

Thanks a lot,
Kareem Moustafa

On Feb 3, 2019, at 4:24 AM, Alan Hamlett <notifications@github.com> wrote:

Do you have a File -> WakaTime API Key menu inside your Xcode?

**Comment by walkah** [comment]
I don't have a `File -> WakaTime API Key` menu... I'm running XCode 10.1 on Mojave. I tried uninstalling wakatime + alcatraz and re-installing.

Any additional steps to try?

**Comment by k4reemMoustafa** [comment]
Upgrading the client as it says there is an upgrade and nothing changed. I also opened previous projects that the plug-in used to work with and also nothing shown on the wakatime Dashboard.

**Comment by walkah** [comment]
Still not working in XCode 10.2 (fresh plugin install)

**Comment by gandarez** [comment]
Tested using `v10.2.1` with success. 

Please give me a feedback @walkah @k4reemMoustafa

**Comment by walkah** [comment]
@gandarez nope, no luck. I uninstalled & reinstalled (per README instructions). I've posted my build log here: https://gist.github.com/walkah/301d3cdb14df0c691eb0e7120e2142a1

I am not prompted to enter my api key (I moved `~/.wakatime.cfg`), there is no menu entry, etc. 

XCode 10.2.1 as well.

**Comment by alanhamlett** [comment]
I'm also not able to reproduce this... just installed the plugin for Xcode 10.2.1 and the `File -> WakaTime API Key` menu is present and plugin working.

<img width="985" alt="Screen Shot 2019-07-04 at 11 08 07 AM" src="https://user-images.githubusercontent.com/522344/60683343-2eb7a080-9e4c-11e9-9073-988329f022d4.png">


Your install log has no errors and says everything worked. Do you get prompted to load bundles when opening Xcode?

**Comment by walkah** [comment]
@alanhamlett interesting. I just tried completely re-installing xcode (not just the plugin) and this time it worked. Not sure why, but this seems to be not an issue.

(I had been using the plugin through several macOS and Xcode upgrades... something must've broken along the way... on both my machines?)

**Comment by gandarez** [comment]
Something has happened with the installation. Hopefully got working.
