### ISSUE TITLE
Not working for xcode 10

### ISSUE THREAD

**Issue by PrashantKT** [wakatime/xcode-wakatime#40]
Need help

I have run command 
curl -fsSL https://raw.githubusercontent.com/wakatime/xcode-wakatime/master/install.sh | sh

and here is last message 

```
** BUILD SUCCEEDED **

Make sure all installed plugins have the latest Xcode compatibility UUID...
Importing self-signed cert to default keychain, select Allow when prompted...
security: SecKeychainItemImport: The specified item already exists in the keychain.
Importing public key to default keychain, select Allow when prompted...
security: SecKeychainItemImport: The specified item already exists in the keychain.
Importing private key to default keychain, select Allow when prompted...
Resigning /Applications/Xcode.app, this may take a while...
/Applications/Xcode.app: replacing existing signature
```
And I have multiple XCode install in my mac  does it matters ?

But now what I need to do ? Where I need to add API key ?

**Comment by gandarez** [comment]
Depending on your machine it should take a while to complete.
<img width="557" alt="Screen Shot 2019-07-03 at 09 05 51" src="https://user-images.githubusercontent.com/782854/60590214-d6ac6b80-9d71-11e9-9ae8-cedeb3d5526f.png">
