### ISSUE TITLE
Support Xcode-beta 11

### ISSUE THREAD

**Issue by yahyatabba** [wakatime/xcode-wakatime#45]
Hello,

Is Wakatime support Xcode-beta 11? and is it support both of Xcode 10 and 11 in the same time?

Thank you

**Comment by alanhamlett** [comment]
Yes, it works but you need to re-run the install script after upgrading:

```
curl -fsSL https://raw.githubusercontent.com/wakatime/xcode-wakatime/master/install.sh | sh
```

To use wakatime with multiple versions of Xcode at the same time, point the install script at each Xcode version's app folder:
```
curl -fsSL https://raw.githubusercontent.com/wakatime/xcode-wakatime/master/install.sh | sh -s custom /Applications/Xcode.app
```

**Comment by alanhamlett** [comment]
Correction, for beta versions make sure to run the install script with beta argument:
```
curl -fsSL https://raw.githubusercontent.com/wakatime/xcode-wakatime/master/install.sh | sh -s beta
```
