### ISSUE TITLE
API menu not appearing in Xcode 11.3

### ISSUE THREAD

**Issue by Matthewspear** [wakatime/xcode-wakatime#46]
I've tried multiple attempts at installing the plugin from `master` and the script runs and completes. Sadly the API key menu does not appear and nor does the `.wakatime.cfg` file appear in my home directory.

I've tried creating the `.wakatime.cfg` file and turning on debug (the line `debug=true` but that doesn't work either.

Do you have any further recommendations for getting wakatime setup?

Thanks – I'm excited to get back to using WakaTime!

**Comment by BryanJBryce** [comment]
@Matthewspear Any reason why you aren't using the latest Xcode version 11.4? I'm using 11.3.1 for a project that has libraries that haven't been updated for 11.4 yet and it works. My problem is that if I install Wakatime for one Xcode it seems to uninstall it for the other.

**Comment by Matthewspear** [comment]
Thanks for the response – I'm having upgrade issues with first upgrading macOS, but will try install it on Xcode 11.4 and respond with an update!

**Comment by Matthewspear** [comment]
Turns out it was my system – I was stuck on macOS 10.15 GM (beta 11) after removing the beta developer profile and not actively keeping on top of my system updates. 

I updated to macOS 10.15.4, installed Xcode 11.4, ran the script and the API window popped up on install. I've check and tested it and I am back in action :)

Thanks for your help @BryanJBryce!
