### ISSUE TITLE
Not compatible with this version of Xcode (12.5.1)

### ISSUE THREAD

**Issue by BillChen2k** [wakatime/xcode-wakatime#55]
Hi, My Xcode version is 12.5.1 (12E507) and I have installed xcode-wakatime with the install script. However the plugin is not available under the File menu and by checking the console I saw the following error message:

```
[MT] PluginLoading: Skipping plug-in at path '/Users/admin/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin' because it is not compatible with this version of Xcode.
[MT] PluginLoading: Skipping plug-in at path '/Users/admin/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' because it is not compatible with this version of Xcode.
```

Is there any solution about this or is wakatime no longer available for Xcode anymore from this Xcode version?

**Comment by alanhamlett** [comment]
Strange... I'm also using `12.5.1 (12E507)` and it's working. Can you try re-running the install script? It's probably related to the `DVTUUID` which updates anytime you upgrade Xcode.app. Re-installing the WakaTime extension fixes it by adding the current Xcode.app's DVTUUID to the WakaTime and Alcatraz extensions.

**Comment by BillChen2k** [comment]
Thanks, uninstalling and reinstalling worked. Before this I had only ran the installation script multiple times without uninstalling.
