### ISSUE TITLE
Cannot install to Xcode v13.2.1

### ISSUE THREAD

**Issue by stockerb** [wakatime/xcode-wakatime#57]
I finally upgraded to Xcode  13.2.1 (13C100) and Wakatime will not install to this version. Is there a way to force install the plugin? Or am I just out of luck?

This is a fresh install on a new development system that IS NOT the M1 platform.

**Comment by alanhamlett** [comment]
I'm also using Xcode `Version 13.2.1 (13C100)` and the install script worked for me. Sometimes if you're afk while installing it will timeout the sudo password prompt. Can you try running the install script again and look for any error messages?

**Comment by stockerb** [comment]
I can understand that occurring however, I am not afk during any installs. I did not see any error messages but I'll try it again.

**Comment by stockerb** [comment]
Here is what I get - 

password to unlock login.keychain:
Importing self-signed cert to default keychain, select Allow when prompted...
1 certificate imported.
Importing public key to default keychain, select Allow when prompted...
security: SecKeychainItemImport: The specified item already exists in the keychain.
Importing private key to default keychain, select Allow when prompted...
Resigning /Applications/Xcode.app, this may take a while...
/Applications/Xcode.app: replacing existing signature
/Applications/Xcode.app: resource fork, Finder information, or similar detritus not allowed

I'm searching for the cause of this - security: SecKeychainItemImport: The specified item already exists in the keychain.

**Comment by alanhamlett** [comment]
That one seems like a warning. The error is `/Applications/Xcode.app: resource fork, Finder information, or similar detritus not allowed`. I'm upgrading my OSX to the latest version to see if I can reproduce it.

**Comment by stockerb** [comment]
I am running on macOS Monterey version 12.1 (21C52)

**Comment by alanhamlett** [comment]
Tested on `MacOS Monterey 12.1 (21C52)` also Intel, and didn't get any error:

```
** BUILD SUCCEEDED **

Cleaning up after installing WakaTime...
Make sure all installed plugins have the latest Xcode compatibility UUID...
password to unlock login.keychain:
Importing self-signed cert to default keychain, select Allow when prompted...
security: SecKeychainItemImport: The specified item already exists in the keychain.
Importing public key to default keychain, select Allow when prompted...
security: SecKeychainItemImport: The specified item already exists in the keychain.
Importing private key to default keychain, select Allow when prompted...
Resigning /Applications/Xcode.app, this may take a while...
/Applications/Xcode.app: replacing existing signature
Finished installing WakaTime. Launching Xcode...
```

The line it's failing on is (verbose flag added):
`sudo codesign -f -V -s XcodeSigner2018 /Applications/Xcode.app`

Try running that line and paste the output here.

**Comment by stockerb** [comment]
Here is what got back -

sudo codesign -f -v -s XcodeSigner2018 /Applications/Xcode.app
/Applications/Xcode.app: replacing existing signature
/Applications/Xcode.app: resource fork, Finder information, or similar detritus not allowed

**Comment by alanhamlett** [comment]
Try:

`xattr -cr /Applications/Xcode.app`

Then re-run:

`sudo codesign -f -v -s XcodeSigner2018 /Applications/Xcode.app`

**Comment by stockerb** [comment]
That workedish - I've been out of coding for awhile and forgot that many things require sudo to run.

For the codesign, I could not use the capital V. I get that it is an invalid option. Using lowercase V worked for me.

I really appreciate your help. I've also cloned your repo in hopes to learn how it works and to see if I can possibly help with the app signing interference with Apple Account.

Thank you again and Happy New Year!
