### ISSUE TITLE
install fails on xcode 13.3

### ISSUE THREAD

**Issue by fatlinesofcode** [wakatime/xcode-wakatime#59]
```
x Alcatraz.xcplugin/Contents/Resources/ATZPackageListTableCellView.nib: Can't replace existing directory with non-directory
x Alcatraz.xcplugin/Contents/Resources/ATZPluginWindowController.nib: Can't replace existing directory with non-directory
x Alcatraz.xcplugin/Contents/Resources/bitbucket_grayscale.tiff
```

<img width="875" alt="Screen Shot 2022-04-05 at 9 14 45 pm" src="https://user-images.githubusercontent.com/505776/161742078-a5fbe08f-ad44-4083-bba4-8f811fb37d71.png">

**Comment by 0xcaffebabe** [comment]
remove the 2 plugin and reinstall work fine for me: https://github.com/wakatime/xcode-wakatime#uninstalling

**Comment by fatlinesofcode** [comment]
thank you, deleting the plugins from `~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins` and re-runs install.sh worked.
