### ISSUE TITLE
Changing API key

### ISSUE THREAD

**Issue by deivuh** [wakatime/xcode-wakatime#6]
Hi,

I inputed a wrong API key after installation. Then I couldn't find any option to change the API key, I've tried uninstalling and installing the package again but it won't ask me for the API key again. How can I change the API Key?

Thanks in advance

**Comment by eltonc-dev** [comment]
Hi Guys,
I trying to do this on xcode 8.2.1, but that option is not displayed. is there another way to change API KEY? 

I my case, when i relaunch de xcode after installed the plugin, it doe's not ask me about the API KEY.

**Comment by alanhamlett** [comment]
If the WakaTime API Key menu is not available, then the plugin is not installed correctly. Have you followed the steps to re-sign Xcode to get plugins working again in Xcode 8?

**Comment by eltonc-dev** [comment]
Hey @alanhamlett , thanks man.
I unistall xcode e made the process all over again and now it's properly working.
