### ISSUE TITLE
Xcode crashes on launch after install

### ISSUE THREAD

**Issue by Matthewspear** [wakatime/xcode-wakatime#65]
Xcode is unresponsive on launch, trying to open working project / new project cause Xcode to crash.

Using Xcode 13.4.1 (Latest at time of post) and script from README.md in this repo.

Attaching crashlog. Particularly noticed the line mentioning WakaTime: `[WakaTime sendHeartbeatWithWrite:]`

[Crash.txt](https://github.com/wakatime/xcode-wakatime/files/8896745/Crash.txt)

**Comment by alanhamlett** [comment]
`NSTask.launch` has been deprecated, so switched to `NSTask.launchAndReturnError` with afa2e1fa77ce630ef3deda5d3937b197c36c3c25.

Can you see if re-installing the xcode-wakatime plugin works now?

**Comment by Matthewspear** [comment]
I've re-installed and have no crashes 🎉

But it doesn't seem to be logging to the dashboard – I tried replacing the API key but still nothing...

Let me know if theres anything I can do to assist debugging it!

**Comment by Matthewspear** [comment]
I've checked again in the dashboard and the API key and it seems with the latest change I'm no longer receiving update to Wakatime from Xcode

**Comment by Matthewspear** [comment]
Update on this – I've got it working, completely uninstalled wakatime (everything = xcode, all dot files, vscode) and then fresh installed it and received time logged in the dashboard

Happy to close this!
