### ISSUE TITLE
Complete Uninstall

### ISSUE THREAD

**Issue by mdewolfe** [wakatime/xcode-wakatime#7]
How would I go about removing Wakatime completely. It was installed via Alcatraz. I have removed the .wakatime files from my home directory. `~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins/` is empty. Is there anywhere else I should look?

**Comment by alanhamlett** [comment]
WakaTime creates a few dot files in your home directory:

`~/.wakatime.cfg`, `~/.wakatime.log`, `~/.wakatime.db`

That and the `Plug-ins/WakaTime` directory is everything.

**Comment by gtkpr** [comment]
I'd like to know how to uninstall too, but on Windows. It crashes Notepadd every time I plug in my HDMI cable to stream stuff.

**Comment by alanhamlett** [comment]
@gtkpr for Notepad++ here are the uninstall instructions: https://wakatime.com/notepad++#uninstall

**Comment by RajChanchal** [comment]
@alanhamlett I want to uninstall from XCode, how can I? It seems to access my keychain apple Id secret keys

**Comment by alanhamlett** [comment]
@RajChanchal run these commands to completely remove WakaTime for Xcode:

```
rm -r "~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin"
rm ~/.wakatime*
sudo security delete-identity -c XcodeSigner -t $(tr -d "\"" <<< `security default-keychain`)
```

**Comment by k4reemMoustafa** [comment]
I updated Xcode to Version 10.0 (10A254a). I was unable to install wakatime plugin. I got this message in the system log:

> com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.Xcode.752): Failed to bootstrap path: path = /Applications/Xcode.app/Contents/XPCServices/com.apple.dt.Xcode.SymbolicateXPCService.xpc, error = 129: The service was superseded by a later version

Please help.
