### ISSUE TITLE
wakatime stops working after xcode 6.2 update

### ISSUE THREAD

**Issue by cakl** [wakatime/xcode-wakatime#8]
After the update to xcode 6.2 wakatime stopped working. I removed the wakatime plugin via alcatraz and re-installed it, but it still doesn't work. 
Then I removed the plugin via terminal and I even removed the .wakatime* files in my home folder. Reinstalled wakatime plugin and I not even get asked for the api key **AND** no wakatime* files were created in my home folder.

What am I doing wrong?

**Comment by alanhamlett** [comment]
I saw the same thing today with 6.2 but after reinstalling the WakaTime plugin it started working.

If the plugin is loaded you should have a `File -> WakaTime API Key` menu item. Do you have this menu item?

**Comment by cakl** [comment]
If you mean the xcode ```File -> WakaTime API Key``` menu, then not, no.

http://cl.ly/image/0E3S1Y2o3E2I

**Comment by alanhamlett** [comment]
Ok, try opening `Window -> Package Manager` which will cause Alcatraz to update the WakaTime plugin to the latest version. Then the `File -> WakaTime API Key` menu should appear and the plugin will work again.

**Comment by cakl** [comment]
I already tried that (see screenshot attached). I even uninstalled all plugins and removed all alcatraz files (including the xcode plugins) via terminal. 

http://cl.ly/image/1d423G290a0R

PS: Is there no possibility to install the plugin via terminal?

**Comment by alanhamlett** [comment]
I don't know of any way to install the WakaTime plugin via terminal without loosing the auto-update feature from Alcatraz. You also need Xcode running to install any plugin, because Alcatraz builds the plugin when installing it.

Can you check for any error messages containing the word `wakatime` or `WakaTime` in your syslog? That's where Xcode writes it's error messages. You can do that by running this terminal command:

    syslog | grep -E "wakatime|WakaTime"

**Comment by cakl** [comment]
I repeatedly see this:
```
Mar 20 19:59:04 2908g-1012-1.hsr.ch Xcode[5955] <Warning>: Updating Repo: /Users/sebastianbock/Library/Application Support/Alcatraz/Plug-ins/WakaTime
Mar 20 20:01:58 2908g-1012-1.hsr.ch Xcode[6082] <Warning>: Cloning Repo: /Users/sebastianbock/Library/Application Support/Alcatraz/Plug-ins/WakaTime
Mar 20 20:02:00 2908g-1012-1.hsr.ch Xcode[6082] <Warning>: Git Clone output: Cloning into '/Users/sebastianbock/Library/Application Support/Alcatraz/Plug-ins/WakaTime'...
Mar 20 20:02:00 2908g-1012-1.hsr.ch xcodebuild[6169] <Warning>: error: InputFile    /Users/sebastianbock/Library/Application Support/Alcatraz/Plug-ins/WakaTime/WakaTime/WakaTime-Prefix.pch 0 1424091265 182 33188... malformed line 10; 'InputFile' should have exactly five arguments
Mar 20 20:02:00 2908g-1012-1.hsr.ch Xcode[6082] <Warning>: Xcodebuild output: === BUILD TARGET WakaTime OF PROJECT WakaTime WITH THE DEFAULT CONFIGURATION (Release) ===
```

**Comment by alanhamlett** [comment]
This looks related to wczekalski/WCGitTagsPlugin#5 and CocoaPods/issues#2638

**Comment by cakl** [comment]
Removing the ```/var/folders/..``` helped. Thanks for the hint.
